server:
  port: 8071

spring:
  # 热重启
  devtools:
    restart:
      enabled: true
      # 生效路径
      additional-paths: src/main/java
      # 排除路径
      additional-exclude: WEB-INF/**
  profiles:
    active: @spring.profiles.active@
  # --------- 数据库配置 -------- #
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #  ---------- hikari config ---------- #
    hikari:
      pool-name: KevinHikariPool
      #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 150
      #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 20
      #连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000
      #空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；
      # 不等于0且小于10秒，会被重置为10秒。
      # 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
      idle-timeout: 500000
      #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 540000
      #连接测试查询
      connection-test-query: SELECT 1

# 海康功能
hikang:
  enable: true

# ------------- 配置 mybatis-plus ----------#
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  mapper-locations: classpath:mapper/*.xml

# 日志
logging:
  file:
    # 日志文件夹名称
    name: logs

# ------------- 配置 下载设置 ---------- #
download:
  # 临时下载文件路径
  tempPath: "E:\\downTemp"
  # vlc播放器的路径
  vlcPath: "lib\\vlc"
