###申请刻录任务
POST http://192.168.99.121:8071/burn/setting
Content-Type: application/json

{
  "taskNum": 2,
  "encryptionType": 1,
  "password": "656",
  "odaSavePath": "E:\\fdfds\\dfdf",
  "callBackUrl": "http://127.0.0.1:8071/burn/callBackTest"
}

### 下载审讯机视频
POST http://192.168.99.121:8071/burn/download
Content-Type: application/json

{
  "taskId": 1,
  "ip": "192.168.99.223",
  "userName": "admin",
  "password": "sjw@2021",
  "channelNo": 1,
  "startTime": "2021-05-06 13:30:00",
  "endTime": "2021-05-06 13:35:00"
}

### 下载文件
POST http://192.168.99.121:8071/burn/file
Content-Type: application/json

{
  "taskId": 2,
  "fileUrl": "http://pics4.baidu.com/feed/03087bf40ad162d93da6bacbb86969ea8813cddf.jpeg?token=93a741e191c542ed5407f4afbc0fb724",
  "odaSavePath": "E:\\fdfds\\dfdf"
}

### 查询刻录父任务信息
GET http://192.168.99.121:8071/burn/burnSetting/1

### 查询下载文件任务信息
GET http://192.168.99.121:8071/burn/burnFile/1

### 查询下载视频任务信息
GET http://192.168.99.121:8071/burn/burnVideo/1
